export const auth = {
  en: {
    welcome: 'Welcome to ConceptScroll',
    welcomeSubtitle: 'Learn smarter with curriculum-aligned content',
    login: 'Login',
    signup: 'Sign Up',
    email: 'Email',
    password: 'Password',
    phone: 'Phone Number',
    phoneNumber: 'Phone Number',
    phoneNumberPlaceholder: 'Enter your 10-digit phone number',
    phoneNumberHelper: "We'll send you a 6-digit OTP",
    invalidPhone: 'Please enter a valid 10-digit phone number',
    otp: 'OTP Code',
    sendOTP: 'Send OTP',
    sendingOTP: 'Sending OTP...',
    requestOTP: 'Request OTP',
    verifyOTP: 'Verify OTP',
    verifyAndLogin: 'Verify & Login',
    verifying: 'Verifying...',
    enterOTPLabel: 'Enter OTP',
    otpPlaceholder: '000000',
    otpHelper: '6-digit code',
    enterValidOTP: 'Please enter the 6-digit OTP',
    changeNumber: 'Change number',
    otpSentTo: 'OTP sent to',
    checkConsole: 'Check browser console for OTP code',
    continueWithGoogle: 'Continue with Google',
    or: 'or',
    firstName: 'First Name',
    lastName: 'Last Name',
    alreadyHaveAccount: 'Already have an account?',
    dontHaveAccount: "Don't have an account?",
    forgotPassword: 'Forgot password?',
    enterOTP: 'Enter the 6-digit code sent to your phone',
    resendOTP: 'Resend OTP',
    otpSent: 'OTP sent successfully',
    invalidOTP: 'Invalid OTP. Please try again.',
    accountNotFound: 'Account not found. Please sign up first.',
    redirectingToSignup: 'Redirecting to sign up...',
    failedToSendOTP: 'Failed to send OTP. Please try again.',
    loginSuccess: 'Login successful',
    signupSuccess: 'Account created successfully',
  },
  hi: {
    welcome: 'ConceptScroll में आपका स्वागत है',
    welcomeSubtitle: 'पाठ्यक्रम-संरेखित सामग्री के साथ स्मार्ट तरीके से सीखें',
    login: 'लॉगिन',
    signup: 'साइन अप',
    email: 'ईमेल',
    password: 'पासवर्ड',
    phone: 'फ़ोन नंबर',
    phoneNumber: 'फ़ोन नंबर',
    phoneNumberPlaceholder: 'अपना 10-अंकीय फ़ोन नंबर दर्ज करें',
    phoneNumberHelper: 'हम आपको 6-अंकीय OTP भेजेंगे',
    invalidPhone: 'कृपया एक मान्य 10-अंकीय फ़ोन नंबर दर्ज करें',
    otp: 'OTP कोड',
    sendOTP: 'OTP भेजें',
    sendingOTP: 'OTP भेजा जा रहा है...',
    requestOTP: 'OTP अनुरोध करें',
    verifyOTP: 'OTP सत्यापित करें',
    verifyAndLogin: 'सत्यापित करें और लॉगिन करें',
    verifying: 'सत्यापित किया जा रहा है...',
    enterOTPLabel: 'OTP दर्ज करें',
    otpPlaceholder: '000000',
    otpHelper: '6-अंकीय कोड',
    enterValidOTP: 'कृपया 6-अंकीय OTP दर्ज करें',
    changeNumber: 'नंबर बदलें',
    otpSentTo: 'OTP भेजा गया',
    checkConsole: 'OTP कोड के लिए ब्राउज़र कंसोल देखें',
    continueWithGoogle: 'Google के साथ जारी रखें',
    or: 'या',
    firstName: 'पहला नाम',
    lastName: 'अंतिम नाम',
    alreadyHaveAccount: 'पहले से खाता है?',
    dontHaveAccount: 'खाता नहीं है?',
    forgotPassword: 'पासवर्ड भूल गए?',
    enterOTP: 'अपने फोन पर भेजा गया 6-अंकीय कोड दर्ज करें',
    resendOTP: 'OTP पुनः भेजें',
    otpSent: 'OTP सफलतापूर्वक भेजा गया',
    invalidOTP: 'अमान्य OTP। कृपया पुनः प्रयास करें।',
    accountNotFound: 'खाता नहीं मिला। कृपया पहले साइन अप करें।',
    redirectingToSignup: 'साइन अप पर रीडायरेक्ट किया जा रहा है...',
    failedToSendOTP: 'OTP भेजने में विफल। कृपया पुनः प्रयास करें।',
    loginSuccess: 'लॉगिन सफल',
    signupSuccess: 'खाता सफलतापूर्वक बनाया गया',
  },
  ta: {
    welcome: 'ConceptScroll இல் வரவேற்கிறோம்',
    welcomeSubtitle: 'பாடத்திட்டம் சீரமைக்கப்பட்ட உள்ளடக்கத்துடன் புத்திசாலித்தனமாக கற்றுக்கொள்ளுங்கல்',
    login: 'உள்நுழைய',
    signup: 'பதிவு செய்ய',
    email: 'மின்னஞ்சல்',
    password: 'கடவுச்சொல்',
    phone: 'தொலைபேசி எண்',
    phoneNumber: 'தொலைபேசி எண்',
    phoneNumberPlaceholder: 'உங்கள் 10-இலக்க தொலைபேசி எண்ணை உள்ளிடவும்',
    phoneNumberHelper: 'நாம் உங்களுக்கு 6-இலக்க ஒட்டைபேசி குறியீட்டை அனுப்புவோம்',
    invalidPhone: 'க௃ப்யாக ஒரு மாதிரியான 10-இலக்க தொலைபேசி எண்ணை உள்ளிடவும்',
    otp: 'OTP குறியீடு',
    sendOTP: 'OTP அனுப்பவும்',
    sendingOTP: 'OTP அனுப்புகிறது...',
    requestOTP: 'OTP கோரவும்',
    verifyOTP: 'OTP சரிபார்க்கவும்',
    verifyAndLogin: 'சரிபார்க்கவும் & உள்நுழைய',
    verifying: 'சரிபார்க்குகிறது...',
    enterOTPLabel: 'OTP உள்ளிடவும்',
    otpPlaceholder: '000000',
    otpHelper: '6-இலக்க குறியீடு',
    enterValidOTP: 'க௃ப்யாக 6-இலக்க ஒட்டைபேசி குறியீட்டை உள்ளிடவும்',
    changeNumber: 'எண்ணை மாற்றவும்',
    otpSentTo: 'OTP அனுப்பப்பட்டது',
    checkConsole: 'OTP குறியீட்டுக்கு பார்க்கவும் வலைப்பட்டியான கம்போசோல்',
    continueWithGoogle: 'Google உடன் தொடரவும்',
    or: 'அல்லது',
    firstName: 'முதல் பெயர்',
    lastName: 'கடைசி பெயர்',
    alreadyHaveAccount: 'ஏற்கனவே கணக்கு உள்ளதா?',
    dontHaveAccount: 'கணக்கு இல்லையா?',
    forgotPassword: 'கடவுச்சொல்லை மறந்துவிட்டீர்களா?',
    enterOTP: 'உங்கள் தொலைபேசிக்கு அனுப்பப்பட்ட 6-இலக்க குறியீட்டை உள்ளிடவும்',
    resendOTP: 'OTP மீண்டும் அனுப்பவும்',
    otpSent: 'OTP வெற்றிகரமாக அனுப்பப்பட்டது',
    invalidOTP: 'தவறான OTP. மீண்டும் முயற்சி செய்யவும்.',
    accountNotFound: 'கணக்கு காணப்படவில்லை. முதலில் பதிவு செய்யவும்.',
    redirectingToSignup: 'பதிவு செய்ய பகுதிக்கு ரி஡ிரெக்ட் செய்யப்படுகிறது...',
    failedToSendOTP: 'OTP அனுப்புவதில் தோல்து. மீண்டும் முயற்சி செய்யவும்.',
    loginSuccess: 'உள்நுழைவு வெற்றிகரமாக',
    signupSuccess: 'கணக்கு வெற்றிகரமாக உருவாக்கப்பட்டது',
  },
  te: {
    welcome: 'ConceptScroll కి స్వాగతం',
    welcomeSubtitle: 'పాఠ్యప్రణాళిక-సమలేఖన కంటెంట్‌తో తెలివిగా నేర్చుకోండి',
    login: 'లాగిన్',
    signup: 'సైన్ అప్',
    email: 'ఇమెయిల్',
    password: 'పాస్‌వర్డ్',
    phone: 'ఫోన్ నంబర్',
    phoneNumber: 'ఫోన్ నంబర్',
    phoneNumberPlaceholder: 'మీ పదిశా నెంబర్‌ను ప్రవేశించండి',
    phoneNumberHelper: 'మేము మీకు 6-అంకెల ఒట్‌టైపి పాస్‌వర్డ్‌ను అపాయించుతాము',
    invalidPhone: 'మీ పదిశా నెంబర్‌ను సరైన రూపంలో ప్రవేశించండి',
    otp: 'OTP కోడ్',
    sendOTP: 'OTP అపాయించండి',
    sendingOTP: 'OTP అపాయించుతోంది...',
    requestOTP: 'OTP అభ్యర్థించండి',
    verifyOTP: 'OTP ధృవీకరించండి',
    verifyAndLogin: 'ధృవీకరించండి & లాగిన్',
    verifying: 'ధృవీకరణ చేయుతోంది...',
    enterOTPLabel: 'OTP ప్రవేశించండి',
    otpPlaceholder: '000000',
    otpHelper: '6-అంకెల కోడ్',
    enterValidOTP: 'మీ సరైన 6-అంకెల OTP ప్రవేశించండి',
    changeNumber: 'సంఖ్యను మార్చండి',
    otpSentTo: 'OTP అపాయించబడింది',
    checkConsole: 'OTP కోడ్ కోసం వెబ్ కంసోల్‌ను చూడండి',
    continueWithGoogle: 'Google తో కొనసాగించండి',
    or: 'లేదా',
    firstName: 'మొదటి పేరు',
    lastName: 'చివరి పేరు',
    alreadyHaveAccount: 'ఇప్పటికే ఖాతా ఉందా?',
    dontHaveAccount: 'ఖాతా లేదా?',
    forgotPassword: 'పాస్‌వర్డ్ మర్చిపోయారా?',
    enterOTP: 'మీ ఫోన్‌కు పంపిన 6-అంకెల కోడ్‌ను నమోదు చేయండి',
    resendOTP: 'OTP మళ్లీ పంపండి',
    otpSent: 'OTP విజయవంతంగా పంపబడింది',
    invalidOTP: 'చెల్లని లేదా గడువు ముగిసిన OTP',
    accountNotFound: 'ఖాతా కనుగొనబడలేదు. మొదట సైన్ అప్ చేయండి.',
    redirectingToSignup: 'సైన్ అప్‌కు రీడిరెక్ట్ చేయబడుతోంది...',
    failedToSendOTP: 'OTP పంపడలేదు. మళ్లీ ప్రయత్నించండి.',
    loginSuccess: 'లాగిన్ విజయవంతం',
    signupSuccess: 'ఖాతా విజయవంతంగా సృష్టించబడింది',
  },
  mr: {
    welcome: 'ConceptScroll मध्ये आपले स्वागत आहे',
    welcomeSubtitle: 'अभ्यासक्रम-संरेखित सामग्रीसह हुशारीने शिका',
    login: 'लॉगिन',
    signup: 'साइन अप',
    email: 'ईमेल',
    password: 'पासवर्ड',
    phone: 'फोन नंबर',
    phoneNumber: 'फोन नंबर',
    phoneNumberPlaceholder: 'तुमच्या 10-अंकी फोन नंबर प्रविष्ट करा',
    phoneNumberHelper: 'आम्ही तुमच्याला 6-अंकी OTP पाठवू शकतो',
    invalidPhone: 'कृपया एक मान्य 10-अंकी फोन नंबर प्रविष्ट करा',
    otp: 'OTP कोड',
    sendOTP: 'OTP पाठवा',
    sendingOTP: 'OTP पाठवत आहे...',
    requestOTP: 'OTP विनंती करा',
    verifyOTP: 'OTP सत्यापित करा',
    verifyAndLogin: 'सत्यापित करा & लॉगिन करा',
    verifying: 'सत्यापित करत आहे...',
    enterOTPLabel: 'OTP प्रविष्ट करा',
    otpPlaceholder: '000000',
    otpHelper: '6-अंकी कोड',
    enterValidOTP: 'कृपया 6-अंकी OTP प्रविष्ट करा',
    changeNumber: 'नंबर बदला',
    otpSentTo: 'OTP पाठवले',
    checkConsole: 'OTP कोड कस्ती आहे त्यासाठी ब्राउज़र कंसोल देखा',
    continueWithGoogle: 'Google सह सुरू ठेवा',
    or: 'किंवा',
    firstName: 'पहिले नाव',
    lastName: 'आडनाव',
    alreadyHaveAccount: 'आधीच खाते आहे?',
    dontHaveAccount: 'खाते नाही?',
    forgotPassword: 'पासवर्ड विसरलात?',
    enterOTP: 'तुमच्या फोनवर पाठवलेला 6-अंकी कोड प्रविष्ट करा',
    resendOTP: 'OTP पुन्हा पाठवा',
    otpSent: 'OTP यशस्वीरित्या पाठवले',
    invalidOTP: 'अवैध OTP. कृपया पुन्हा प्रयास करा.',
    accountNotFound: 'खाता नाही मिळाला. कृपया पहिले साइन अप करा.',
    redirectingToSignup: 'साइन अप पर रीडायरेक्ट किया जा रहा है...',
    failedToSendOTP: 'OTP पाठवण्यात विफल. कृपया पुन्हा प्रयास करा.',
    loginSuccess: 'लॉगिन यशस्वी',
    signupSuccess: 'खाते यशस्वीरित्या तयार केले',
  },
  bn: {
    welcome: 'ConceptScroll এ স্বাগতম',
    welcomeSubtitle: 'পাঠ্যক্রম-সংযুক্ত বিষয়বস্তু সহ স্মার্টভাবে শিখুন',
    login: 'লগইন',
    signup: 'সাইন আপ',
    email: 'ইমেইল',
    password: 'পাসওয়ার্ড',
    phone: 'ফোন নম্বর',
    phoneNumber: 'ফোন নম্বর',
    phoneNumberPlaceholder: 'আপনার 10-অংকের ফোন নম্বর প্রবেশ করুন',
    phoneNumberHelper: 'আমরা আপনাকে 6-অংকের OTP পাঠাবো',
    invalidPhone: 'অনুগ্রহ করে একটি মান্য 10-অংকের ফোন নম্বর প্রবেশ করুন',
    otp: 'OTP কোড',
    sendOTP: 'OTP পাঠান',
    sendingOTP: 'OTP পাঠানো হচ্ছে...',
    requestOTP: 'OTP অনুরোধ করুন',
    verifyOTP: 'OTP যাচাই করুন',
    verifyAndLogin: 'যাচাই করুন & লগইন করুন',
    verifying: 'যাচাই করা হচ্ছে...',
    enterOTPLabel: 'OTP প্রবেশ করুন',
    otpPlaceholder: '000000',
    otpHelper: '6-অংকের কোড',
    enterValidOTP: 'অনুগ্রহ করে 6-অংকের OTP প্রবেশ করুন',
    changeNumber: 'নম্বর পরিবর্তন করুন',
    otpSentTo: 'OTP পাঠানো হয়েছে',
    checkConsole: 'OTP কোড পেতে ব্রাউজার কনসোল দেখুন',
    continueWithGoogle: 'Google এর সাথে চালিয়ে যান',
    or: 'অথবা',
    firstName: 'প্রথম নাম',
    lastName: 'শেষ নাম',
    alreadyHaveAccount: 'ইতিমধ্যে অ্যাকাউন্ট আছে?',
    dontHaveAccount: 'অ্যাকাউন্ট নেই?',
    forgotPassword: 'পাসওয়ার্ড ভুলে গেছেন?',
    enterOTP: 'আপনার ফোনে পাঠানো 6-সংখ্যার কোড প্রবেশ করন',
    resendOTP: 'OTP পুনরায় পাঠান',
    otpSent: 'OTP সফলভাবে পাঠানো হয়েছে',
    invalidOTP: 'অবৈধ OTP. অনুগ্রহ করে আবার চেষ্টা করুন।',
    accountNotFound: 'অ্যাকাউন্ট পাওয়া যায়নি। অনুগ্রহ করে প্রথমে সাইন আপ করুন।',
    redirectingToSignup: 'সাইন আপ পর রিডায়েক্ট করা হচ্ছে...',
    failedToSendOTP: 'OTP পাঠানো হয়নি। অনুগ্রহ করে আবার চেষ্টা করুন।',
    loginSuccess: 'লগইন সফল',
    signupSuccess: 'অ্যাকাউন্ট সফলভাবে তৈরি হয়েছে',
  },
};