import { Localization } from './index';

export const commonStrings: Localization = {
  en: {
    // General
    appName: "ConceptScroll",
    loading: "Loading...",
    error: "Something went wrong",
    retry: "Retry",
    cancel: "Cancel",
    submit: "Submit",
    save: "Save",
    edit: "Edit",
    delete: "Delete",
    next: "Next",
    previous: "Previous",
    back: "Back",
    continue: "Continue",
    seeAll: "See All",
    search: "Search",
    noResults: "No results found",
    
    // Navigation
    home: "Home",
    dashboard: "Dashboard",
    public: "Public",
    feed: "Feed",
    explore: "Explore",
    focus: "Focus",
    quizArena: "Quiz Arena",
    streaks: "Streaks",
    profile: "Profile",
    notifications: "Notifications",
    messages: "Messages",
    settings: "Settings",
    
    // Navigation (for nav links)
    navHome: "Home",
    navDashboard: "Dashboard",
    navExplore: "Explore",
    navFocus: "Focus",
    navQuizArena: "Quiz Arena",
    navStreaks: "Streaks",
    
    // Actions
    signIn: "Sign In",
    signUp: "Sign Up",
    logIn: "Log In",
    logOut: "Log Out",
    joinNow: "Join Now",
    getStarted: "Get Started",
    tryNow: "Try Now",
    ctaTryNow: "Try Now",
    learnMore: "Learn More",
    
    // Footer
    footerAbout: "About",
    footerHelp: "Help",
    footerTeachers: "Teachers' Corner",
    footerFeedback: "Feedback",
    footerPrivacy: "Privacy",
    footerTerms: "Terms",
    footerCreator: "Become a Creator",
    footerCopyright: "© 2025 ConceptScroll. All rights reserved.",
    
    // Language Switcher
    switchToHindi: "हिंदी में देखें",
    switchToEnglish: "View in English",
    
    // Error Messages
    errorNetworkFailed: "Network connection failed",
    errorServerError: "Server error occurred",
    errorAuthFailed: "Authentication failed",
    errorPermissionDenied: "Permission denied",
    errorInvalidInput: "Invalid input provided",
    
    // Error Pages
    error404Title: "Page Not Found",
    error404Subtitle: "Oops! The page you're looking for doesn't exist.",
    error404Description: "It seems you've found a page that doesn't exist. Don't worry, it happens to the best of us!",
    errorGenericTitle: "Something Went Wrong",
    errorGenericSubtitle: "We're experiencing some technical difficulties.",
    errorGenericDescription: "Our team has been notified and is working to fix this issue. Please try again in a few moments.",
    errorNetworkTitle: "Network Error",
    errorNetworkDescription: "Your internet connection seems slow or interrupted. Please check your connection.",
    errorServerTitle: "Server Error", 
    errorServerDescription: "There's an issue with our servers. Our team is working to fix this.",
    errorApplicationTitle: "Application Error",
    errorApplicationDescription: "There's a technical issue with the application. Refreshing the page might help.",
    errorBackToHome: "Back to Home",
    errorGoToLogin: "Go to Login",
    errorTryAgain: "Try Again",
    errorContactSupport: "Contact Support",
    errorRefreshPage: "Refresh Page",
    errorReportSent: "Error report has been sent. Thank you!",
    
    // Error page content
    errorDetails: "Error Details",
    errorId: "Error ID: ",
    errorReportError: "Report Error",
    errorWhatCanTry: "What You Can Try:",
    errorRefreshPageTip: "Refresh the page (Ctrl+R or F5)",
    errorCheckConnection: "Check your internet connection",
    errorClearCache: "Clear your browser cache",
    errorTryLater: "Try again in a few minutes",
    errorDontGiveUp: "Don't Give Up!",
    errorProblemSolution: "Every problem has a solution. Just like you solve difficult problems in your studies, this will be fixed too.",
    
    // 404 page content
    notFoundSearchElse: "Search for Something Else",
    notFoundSearchDescription: "Maybe you were looking for something else? Try using our search feature.",
    notFoundSearchPlaceholder: "Search subjects, chapters...",
    notFoundStudyMaterials: "Study Materials",
    notFoundStudyDescription: "Check out notes and chapters for your subjects",
    notFoundQuizArena: "Quiz Arena",
    notFoundQuizDescription: "Take part in daily challenges",
    notFoundCommunity: "Community",
    notFoundCommunityDescription: "Connect with other students",
    notFoundLearningNeverStops: "Learning Never Stops!",
    notFoundLearningMessage: "Every mistake is a learning opportunity. Let's explore something new!",
    
    // Time Formats
    today: "Today",
    yesterday: "Yesterday",
    minutesAgo: "{0} minutes ago",
    hoursAgo: "{0} hours ago",
    daysAgo: "{0} days ago",
    
    // UI Elements
    closeButton: "Close",
    menuOpen: "Open Menu",
    menuClose: "Close Menu",
    showMore: "Show More",
    showLess: "Show Less",
    filter: "Filter",
    sort: "Sort",
  },
  hi: {
    // General
    appName: "कॉन्सेप्ट्स स्क्रॉल",
    loading: "लोड हो रहा है...",
    error: "कुछ गलत हो गया",
    retry: "पुनः प्रयास करें",
    cancel: "रद्द करें",
    submit: "सबमिट करें",
    save: "सेव करें",
    edit: "संपादित करें",
    delete: "हटाएं",
    next: "अगला",
    previous: "पिछला",
    back: "वापस",
    continue: "जारी रखें",
    seeAll: "सभी देखें",
    search: "खोजें",
    noResults: "कोई परिणाम नहीं मिला",
    // Navigation
    home: "होम",
    dashboard: "डैशबोर्ड",
    public: "पब्लिक",
    feed: "फीड",
    explore: "एक्सप्लोर",
    focus: "फोकस",
    quizArena: "क्विज़ अरेना",
    streaks: "स्ट्रीक्स",
    profile: "प्रोफाइल",
    notifications: "नोटिफिकेशन",
    messages: "संदेश",
    settings: "सेटिंग्स",
    
    // Navigation (for nav links)
    navHome: "होम",
    navDashboard: "डैशबोर्ड",
    navExplore: "एक्सप्लोर",
    navFocus: "फोकस",
    navQuizArena: "क्विज़ अरेना",
    navStreaks: "स्ट्रीक्स",
    
    // Actions
    signIn: "साइन इन करें",
    signUp: "साइन अप करें",
    logIn: "लॉग इन करें",
    logOut: "लॉग आउट करें",
    joinNow: "अभी जुड़ें",
    getStarted: "शुरू करें",
    tryNow: "अभी आज़माएं",
    ctaTryNow: "अभी आज़माएं",
    learnMore: "और जानें",
    
    // Footer
    footerAbout: "हमारे बारे में",
    footerHelp: "सहायता",
    footerTeachers: "शिक्षक कॉर्नर",
    footerFeedback: "फीडबैक",
    footerPrivacy: "प्राइवेसी",
    footerTerms: "नियम",
    footerCreator: "क्रिएटर बनें",
    footerCopyright: "© 2025 कॉन्सेप्ट्स स्क्रॉल. सर्वाधिकार सुरक्षित।",
    
    // Language Switcher
    switchToHindi: "हिंदी में देखें",
    switchToEnglish: "View in English",
    
    // Error Messages
    errorNetworkFailed: "नेटवर्क कनेक्शन विफल हुआ",
    errorServerError: "सर्वर त्रुटि हुई",
    errorAuthFailed: "प्रमाणीकरण विफल हुआ",
    errorPermissionDenied: "अनुमति अस्वीकृत",
    errorInvalidInput: "अमान्य इनपुट प्रदान किया गया",
    
    // Error Pages
    error404Title: "पृष्ठ नहीं मिला",
    error404Subtitle: "ओह! आप जो पृष्ठ खोज रहे हैं वह मौजूद नहीं है।",
    error404Description: "लगता है आपको एक ऐसा पृष्ठ मिला है जो मौजूद नहीं है। चिंता न करें, यह हम सभी के साथ होता है!",
    errorGenericTitle: "कुछ गलत हो गया",
    errorGenericSubtitle: "हम कुछ तकनीकी कठिनाइयों का सामना कर रहे हैं।",
    errorGenericDescription: "हमारी टीम को सूचना दे दी गई है और वे इस समस्या को ठीक करने पर काम कर रहे हैं। कृपया कुछ क्षणों में पुनः प्रयास करें।",
    errorNetworkTitle: "नेटवर्क त्रुटि",
    errorNetworkDescription: "आपका इंटरनेट कनेक्शन धीमा है या बाधित है। कृपया अपना कनेक्शन जांचें।",
    errorServerTitle: "सर्वर त्रुटि",
    errorServerDescription: "हमारे सर्वर में कुछ समस्या है। हमारी टीम इसे ठीक करने पर काम कर रही है।",
    errorApplicationTitle: "एप्लिकेशन त्रुटि",
    errorApplicationDescription: "एप्लिकेशन में एक तकनीकी समस्या आई है। पृष्ठ को रीफ्रेश करने से मदद मिल सकती है।",
    errorBackToHome: "होम पर वापस जाएं",
    errorGoToLogin: "लॉगिन पर जाएं",
    errorTryAgain: "पुनः प्रयास करें",
    errorContactSupport: "सहायता से संपर्क करें",
    errorRefreshPage: "पृष्ठ रीफ्रेश करें",
    errorReportSent: "त्रुटि रिपोर्ट भेज दी गई है। धन्यवाद!",
    
    // Error page content
    errorDetails: "त्रुटि विवरण",
    errorId: "त्रुटि ID: ",
    errorReportError: "त्रुटि रिपोर्ट करें",
    errorWhatCanTry: "क्या आज़मा सकते हैं:",
    errorRefreshPageTip: "पृष्ठ को रीफ्रेश करें (Ctrl+R या F5)",
    errorCheckConnection: "अपना इंटरनेट कनेक्शन जांचें",
    errorClearCache: "ब्राउज़र कैश साफ़ करें",
    errorTryLater: "कुछ मिनट बाद पुनः प्रयास करें",
    errorDontGiveUp: "हार नहीं मानते!",
    errorProblemSolution: "हर समस्या का समाधान होता है। जैसे आप पढ़ाई में मुश्किलों को हल करते हैं, वैसे ही यह भी ठीक हो जाएगा।",
    
    // 404 page content
    notFoundSearchElse: "कुछ और खोजें",
    notFoundSearchDescription: "शायद आप कुछ और खोज रहे थे? हमारे खोज फ़ीचर का उपयोग करें।",
    notFoundSearchPlaceholder: "विषय, अध्याय खोजें...",
    notFoundStudyMaterials: "अध्ययन सामग्री",
    notFoundStudyDescription: "अपने विषयों के लिए नोट्स और अध्याय देखें",
    notFoundQuizArena: "क्विज़ एरेना",
    notFoundQuizDescription: "दैनिक चुनौतियों में भाग लें",
    notFoundCommunity: "कम्युनिटी",
    notFoundCommunityDescription: "अन्य छात्रों से जुड़ें",
    notFoundLearningNeverStops: "सीखना कभी नहीं रुकता!",
    notFoundLearningMessage: "हर गलती एक सीखने का अवसर है। चलिए कुछ नया सीखते हैं!",
    
    // Time Formats
    today: "आज",
    yesterday: "कल",
    minutesAgo: "{0} मिनट पहले",
    hoursAgo: "{0} घंटे पहले",
    daysAgo: "{0} दिन पहले",
    
    // UI Elements
    closeButton: "बंद करें",
    menuOpen: "मेन्यू खोलें",
    menuClose: "मेन्यू बंद करें",
    showMore: "और दिखाएं",
    showLess: "कम दिखाएं",
    filter: "फ़िल्टर",
    sort: "क्रमबद्ध करें",
  }
};
