// Dashboard localization strings
export const dashboardStrings = {
  en: {
    title: "Your Dashboard",
    dailyGoal: "Daily Goal",
    setGoal: "Set a Goal",
    completeGoal: "Complete Goal",
    quiz: "Quiz",
    lastQuizScore: "Last Quiz Score",
    focusStudy: "Focus Study",
    lastFocusSession: "Last Focus Session",
    challenge: "Challenge",
    latestChallenge: "Latest Challenge",
    loading: "Loading...",
    noData: "No data available",
    minutes: "minutes",
    currentGoal: "Current Goal",
    testKnowledge: "Test Your Knowledge",
    lastQuiz: "Last Quiz",
    takeQuiz: "Take a Quiz",
    lastFocus: "Last Focus Session",
    startFocus: "Start Focus Session",
    joinChallenges: "Join Challenges",
    joinNow: "Join Now",
    viewChallenges: "View Challenges",
    // New strings for enhanced dashboard
    streakCount: "day streak",
    todayProgress: "Today's Progress",
    completeToday: "complete today",
    studyNow: "Study Now",
    wellDone: "Well Done!",
    improveScore: "Keep Improving!",
    readyForQuiz: "Ready for a challenge?",
    focusTime: "Focus Time",
    challengeActive: "Active Challenge",
    participants: "participants",
    timeLeft: "left",
    quickActions: "Quick Actions",
    notes: "Notes",
    progress: "Progress",
    community: "Community",
    settings: "Settings",
    // Adding some from common if needed specific here
    hello: "Hello, {name}! 👋",
    readyToLearn: "Ready to learn something new today?",
    days: "Days",
    xp: "XP",
    level: "Level",
    totalPoints: "Total Points",
    currentLevel: "Current Level",
    conceptFeed: "Concept Feed",
    scrollLearn: "Scroll & Learn",
    dailyQuiz: "Daily Quiz",
    testYourself: "Test Yourself",
    aiGrader: "AI Grader",
    checkAnswers: "Check Answers",
    leaderboard: "Leaderboard",
    viewRankings: "View Rankings",
    continueLearning: "Continue Learning",
    viewAll: "View All",
    achievements: "Achievements",
    upgradeToPremium: "Upgrade to Premium",
    unlockUnlimited: "Unlock unlimited AI grading, detailed analytics, and more!",
    viewPlans: "View Plans"
  },
  hi: {
    title: "आपका डैशबोर्ड",
    dailyGoal: "दैनिक लक्ष्य",
    setGoal: "लक्ष्य सेट करें",
    completeGoal: "लक्ष्य पूरा करें",
    quiz: "प्रश्नोत्तरी",
    lastQuizScore: "अंतिम प्रश्नोत्तरी स्कोर",
    focusStudy: "फोकस अध्ययन",
    lastFocusSession: "अंतिम फोकस सत्र",
    challenge: "चुनौती",
    latestChallenge: "नवीनतम चुनौती",
    loading: "लोड हो रहा है...",
    noData: "कोई डेटा उपलब्ध नहीं है",
    minutes: "मिनट",
    currentGoal: "वर्तमान लक्ष्य",
    testKnowledge: "अपने ज्ञान का परीक्षण करें",
    lastQuiz: "अंतिम प्रश्नोत्तरी",
    takeQuiz: "एक प्रश्नोत्तरी लें",
    lastFocus: "अंतिम फोकस सत्र",
    startFocus: "फोकस सत्र शुरू करें",
    joinChallenges: "चुनौतियों में शामिल हों",
    joinNow: "अब शामिल हों",
    viewChallenges: "चुनौतियाँ देखें",
    // New strings for enhanced dashboard
    streakCount: "दिन की स्ट्रीक",
    todayProgress: "आज की प्रगति",
    completeToday: "आज पूरा करें",
    studyNow: "अभी अध्ययन करें",
    wellDone: "बहुत बढ़िया!",
    improveScore: "सुधार जारी रखें!",
    readyForQuiz: "चुनौती के लिए तैयार?",
    focusTime: "फोकस टाइम",
    challengeActive: "सक्रिय चुनौती",
    participants: "प्रतिभागी",
    timeLeft: "बचा है",
    quickActions: "त्वरित कार्य",
    notes: "नोट्स",
    progress: "प्रगति",
    community: "समुदाय",
    settings: "सेटिंग्स",
    hello: "नमस्ते, {name}! 👋",
    readyToLearn: "आज कुछ नया सीखने के लिए तैयार हैं?",
    days: "दिन",
    xp: "XP",
    level: "लेवल",
    totalPoints: "कुल अंक",
    currentLevel: "वर्तमान लेवल",
    conceptFeed: "कॉन्सेप्ट फीड",
    scrollLearn: "स्क्रॉल करें और सीखें",
    dailyQuiz: "दैनिक क्विज़",
    testYourself: "खुद को परखें",
    aiGrader: "AI ग्रेडर",
    checkAnswers: "उत्तर जांचें",
    leaderboard: "लीडरबोर्ड",
    viewRankings: "रैंकिंग देखें",
    continueLearning: "सीखना जारी रखें",
    viewAll: "सभी देखें",
    achievements: "उपलब्धियां",
    upgradeToPremium: "प्रीमियम में अपग्रेड करें",
    unlockUnlimited: "असीमित AI ग्रेडिंग, विस्तृत एनालिटिक्स और बहुत कुछ अनलॉक करें!",
    viewPlans: "प्लान देखें"
  }
};
