export const feed = {
  en: {
    home: 'Home',
    explore: 'Explore',
    bookmarks: 'Bookmarks',
    filters: 'Filters',
    sortBy: 'Sort By',
    recent: 'Recent',
    popular: 'Popular',
    trending: 'Trending',
    subjects: 'Subjects',
    types: 'Types',
    chapters: 'Chapters',
    applyFilters: 'Apply Filters',
    clearFilters: 'Clear Filters',
    note: 'Note',
    quiz: 'Quiz',
    poll: 'Poll',
    like: 'Like',
    liked: 'Liked',
    comment: 'Comment',
    comments: 'Comments',
    share: 'Share',
    bookmark: 'Bookmark',
    bookmarked: 'Bookmarked',
    vote: 'Vote',
    votes: 'votes',
    readMore: 'Read more',
    readLess: 'Read less',
    viewAllComments: 'View all comments',
    addComment: 'Add a comment...',
    postComment: 'Post',
    reply: 'Reply',
    delete: 'Delete',
    edit: 'Edit',
    report: 'Report',
    noContent: 'No content available',
    loadMore: 'Load More',
    refreshFeed: 'Pull to refresh',
    shareVia: 'Share via',
    copyLink: 'Copy link',
    linkCopied: 'Link copied!',
  },
  hi: {
    home: 'होम',
    explore: 'एक्सप्लोर',
    bookmarks: 'बुकमार्क',
    filters: 'फ़िल्टर',
    sortBy: 'क्रमबद्ध करें',
    recent: 'हाल का',
    popular: 'लोकप्रिय',
    trending: 'ट्रेंडिंग',
    subjects: 'विषय',
    types: 'प्रकार',
    chapters: 'अध्याय',
    applyFilters: 'फ़िल्टर लागू करें',
    clearFilters: 'फ़िल्टर साफ़ करें',
    note: 'नोट',
    quiz: 'प्रश्नोत्तरी',
    poll: 'पोल',
    like: 'पसंद',
    liked: 'पसंद किया',
    comment: 'टिप्पणी',
    comments: 'टिप्पणियाँ',
    share: 'साझा करें',
    bookmark: 'बुकमार्क',
    bookmarked: 'बुकमार्क किया गया',
    vote: 'वोट',
    votes: 'वोट',
    readMore: 'और पढ़ें',
    readLess: 'कम पढ़ें',
    viewAllComments: 'सभी टिप्पणियाँ देखें',
    addComment: 'एक टिप्पणी जोड़ें...',
    postComment: 'पोस्ट',
    reply: 'जवाब दें',
    delete: 'हटाएं',
    edit: 'संपादित करें',
    report: 'रिपोर्ट करें',
    noContent: 'कोई सामग्री उपलब्ध नहीं',
    loadMore: 'और लोड करें',
    refreshFeed: 'रीफ्रेश करने के लिए खींचें',
    shareVia: 'इसके माध्यम से साझा करें',
    copyLink: 'लिंक कॉपी करें',
    linkCopied: 'लिंक कॉपी किया गया!',
  },
  ta: {
    home: 'முகப்பு',
    explore: 'ஆராயுங்கள்',
    bookmarks: 'புத்தகக்குறிகள்',
    filters: 'வடிப்பான்கள்',
    sortBy: 'வரிசைப்படுத்து',
    recent: 'சமீபத்திய',
    popular: 'பிரபலமான',
    trending: 'டிரெண்டிங்',
    subjects: 'பாடங்கள்',
    types: 'வகைகள்',
    chapters: 'அத்தியாயங்கள்',
    applyFilters: 'வடிப்பான்களைப் பயன்படுத்து',
    clearFilters: 'வடிப்பான்களை அழி',
    note: 'குறிப்பு',
    quiz: 'வினாடி வினா',
    poll: 'கருத்துக் கணிப்பு',
    like: 'விருப்பம்',
    liked: 'விரும்பப்பட்டது',
    comment: 'கருத்து',
    comments: 'கருத்துகள்',
    share: 'பகிர்',
    bookmark: 'புத்தகக்குறி',
    bookmarked: 'புத்தகக்குறியிடப்பட்டது',
    vote: 'வாக்களி',
    votes: 'வாக்குகள்',
    readMore: 'மேலும் படிக்கவும்',
    readLess: 'குறைவாக படிக்கவும்',
    viewAllComments: 'அனைத்து கருத்துகளையும் காண்க',
    addComment: 'ஒரு கருத்தைச் சேர்க்கவும்...',
    postComment: 'இடுகை',
    reply: 'பதிலளி',
    delete: 'நீக்கு',
    edit: 'திருத்து',
    report: 'புகார் செய்',
    noContent: 'உள்ளடக்கம் இல்லை',
    loadMore: 'மேலும் ஏற்று',
    refreshFeed: 'புதுப்பிக்க இழுக்கவும்',
    shareVia: 'வழியாக பகிர்',
    copyLink: 'இணைப்பை நகலெடு',
    linkCopied: 'இணைப்பு நகலெடுக்கப்பட்டது!',
  },
  te: {
    home: 'హోమ్',
    explore: 'అన్వేషించు',
    bookmarks: 'బుక్‌మార్క్‌లు',
    filters: 'ఫిల్టర్లు',
    sortBy: 'క్రమబద్ధీకరించు',
    recent: 'ఇటీవలి',
    popular: 'ప్రజాదరణ పొందిన',
    trending: 'ట్రెండింగ్',
    subjects: 'విషయాలు',
    types: 'రకాలు',
    chapters: 'అధ్యాయాలు',
    applyFilters: 'ఫిల్టర్‌లను వర్తింపజేయండి',
    clearFilters: 'ఫిల్టర్‌లను క్లియర్ చేయండి',
    note: 'గమనిక',
    quiz: 'క్విజ్',
    poll: 'పోల్',
    like: 'ఇష్టం',
    liked: 'ఇష్టపడ్డారు',
    comment: 'వ్యాఖ్య',
    comments: 'వ్యాఖ్యలు',
    share: 'షేర్ చేయండి',
    bookmark: 'బుక్‌మార్క్',
    bookmarked: 'బుక్‌మార్క్ చేయబడింది',
    vote: 'ఓటు',
    votes: 'ఓట్లు',
    readMore: 'మరింత చదవండి',
    readLess: 'తక్కువ చదవండి',
    viewAllComments: 'అన్ని వ్యాఖ్యలను వీక్షించండి',
    addComment: 'వ్యాఖ్యను జోడించండి...',
    postComment: 'పోస్ట్',
    reply: 'ప్రత్యుత్తరం',
    delete: 'తొలగించు',
    edit: 'సవరించు',
    report: 'నివేదించు',
    noContent: 'కంటెంట్ అందుబాటులో లేదు',
    loadMore: 'మరింత లోడ్ చేయండి',
    refreshFeed: 'రిఫ్రెష్ చేయడానికి లాగండి',
    shareVia: 'ద్వారా షేర్ చేయండి',
    copyLink: 'లింక్ కాపీ చేయండి',
    linkCopied: 'లింక్ కాపీ చేయబడింది!',
  },
  mr: {
    home: 'होम',
    explore: 'एक्सप्लोर',
    bookmarks: 'बुकमार्क',
    filters: 'फिल्टर',
    sortBy: 'क्रमवारी लावा',
    recent: 'अलीकडील',
    popular: 'लोकप्रिय',
    trending: 'ट्रेंडिंग',
    subjects: 'विषय',
    types: 'प्रकार',
    chapters: 'प्रकरणे',
    applyFilters: 'फिल्टर लागू करा',
    clearFilters: 'फिल्टर साफ करा',
    note: 'नोट',
    quiz: 'प्रश्नमंजुषा',
    poll: 'मतदान',
    like: 'आवडले',
    liked: 'आवडले',
    comment: 'टिप्पणी',
    comments: 'टिप्पण्या',
    share: 'शेअर',
    bookmark: 'बुकमार्क',
    bookmarked: 'बुकमार्क केले',
    vote: 'मत',
    votes: 'मते',
    readMore: 'अधिक वाचा',
    readLess: 'कमी वाचा',
    viewAllComments: 'सर्व टिप्पण्या पहा',
    addComment: 'टिप्पणी जोडा...',
    postComment: 'पोस्ट',
    reply: 'उत्तर द्या',
    delete: 'हटवा',
    edit: 'संपादित करा',
    report: 'तक्रार करा',
    noContent: 'सामग्री उपलब्ध नाही',
    loadMore: 'अधिक लोड करा',
    refreshFeed: 'रिफ्रेश करण्यासाठी खेचा',
    shareVia: 'द्वारे शेअर करा',
    copyLink: 'लिंक कॉपी करा',
    linkCopied: 'लिंक कॉपी केली!',
  },
  bn: {
    home: 'হোম',
    explore: 'এক্সপ্লোর',
    bookmarks: 'বুকমার্ক',
    filters: 'ফিল্টার',
    sortBy: 'সাজান',
    recent: 'সাম্প্রতিক',
    popular: 'জনপ্রিয়',
    trending: 'ট্রেন্ডিং',
    subjects: 'বিষয়',
    types: 'ধরন',
    chapters: 'অধ্যায়',
    applyFilters: 'ফিল্টার প্রয়োগ করুন',
    clearFilters: 'ফিল্টার সাফ করুন',
    note: 'নোট',
    quiz: 'কুইজ',
    poll: 'পোল',
    like: 'পছন্দ',
    liked: 'পছন্দ করা হয়েছে',
    comment: 'মন্তব্য',
    comments: 'মন্তব্যসমূহ',
    share: 'শেয়ার',
    bookmark: 'বুকমার্ক',
    bookmarked: 'বুকমার্ক করা হয়েছে',
    vote: 'ভোট',
    votes: 'ভোট',
    readMore: 'আরও পড়ুন',
    readLess: 'কম পড়ুন',
    viewAllComments: 'সমস্ত মন্তব্য দেখুন',
    addComment: 'একটি মন্তব্য যোগ করুন...',
    postComment: 'পোস্ট',
    reply: 'উত্তর',
    delete: 'মুছুন',
    edit: 'সম্পাদনা',
    report: 'রিপোর্ট',
    noContent: 'কোন বিষয়বস্তু উপলব্ধ নেই',
    loadMore: 'আরও লোড করুন',
    refreshFeed: 'রিফ্রেশ করতে টানুন',
    shareVia: 'মাধ্যমে শেয়ার করুন',
    copyLink: 'লিঙ্ক কপি করুন',
    linkCopied: 'লিঙ্ক কপি হয়েছে!',
  },
};
