export const library = {
  en: {
    title: 'Library',
    mySubjects: 'My Subjects',
    allSubjects: 'All Subjects',
    books: 'Books',
    chapters: 'Chapters',
    notes: 'Notes',
    quizzes: 'Quizzes',
    qa: 'Q&A',
    searchPlaceholder: 'Search for books, chapters...',
    noBooks: 'No books found',
    noChapters: 'No chapters available',
    noNotes: 'No notes available',
    noQuizzes: 'No quizzes available',
    startReading: 'Start Reading',
    continueReading: 'Continue Reading',
    takeQuiz: 'Take Quiz',
    viewDetails: 'View Details',
    chapterNumber: 'Chapter',
    totalChapters: 'chapters',
    notesCount: 'notes',
    quizzesCount: 'quizzes',
  },
  hi: {
    title: 'पुस्तकालय',
    mySubjects: 'मेरे विषय',
    allSubjects: 'सभी विषय',
    books: 'पुस्तकें',
    chapters: 'अध्याय',
    notes: 'नोट्स',
    quizzes: 'प्रश्नोत्तरी',
    qa: 'प्रश्न और उत्तर',
    searchPlaceholder: 'पुस्तकें, अध्याय खोजें...',
    noBooks: 'कोई पुस्तकें नहीं मिलीं',
    noChapters: 'कोई अध्याय उपलब्ध नहीं',
    noNotes: 'कोई नोट्स उपलब्ध नहीं',
    noQuizzes: 'कोई प्रश्नोत्तरी उपलब्ध नहीं',
    startReading: 'पढ़ना शुरू करें',
    continueReading: 'पढ़ना जारी रखें',
    takeQuiz: 'प्रश्नोत्तरी लें',
    viewDetails: 'विवरण देखें',
    chapterNumber: 'अध्याय',
    totalChapters: 'अध्याय',
    notesCount: 'नोट्स',
    quizzesCount: 'प्रश्नोत्तरी',
  },
  ta: {
    title: 'நூலகம்',
    mySubjects: 'எனது பாடங்கள்',
    allSubjects: 'அனைத்து பாடங்கள்',
    books: 'புத்தகங்கள்',
    chapters: 'அத்தியாயங்கள்',
    notes: 'குறிப்புகள்',
    quizzes: 'வினாடி வினாக்கள்',
    qa: 'கே&ஏ',
    searchPlaceholder: 'புத்தகங்கள், அத்தியாயங்களைத் தேடுங்கள்...',
    noBooks: 'புத்தகங்கள் எதுவும் இல்லை',
    noChapters: 'அத்தியாயங்கள் எதுவும் இல்லை',
    noNotes: 'குறிப்புகள் எதுவும் இல்லை',
    noQuizzes: 'வினாடி வினாக்கள் எதுவும் இல்லை',
    startReading: 'படிக்கத் தொடங்குங்கள்',
    continueReading: 'தொடர்ந்து படியுங்கள்',
    takeQuiz: 'வினாடி வினா எடுக்கவும்',
    viewDetails: 'விவரங்களைக் காண்க',
    chapterNumber: 'அத்தியாயம்',
    totalChapters: 'அத்தியாயங்கள்',
    notesCount: 'குறிப்புகள்',
    quizzesCount: 'வினாடி வினாக்கள்',
  },
  te: {
    title: 'లైబ్రరీ',
    mySubjects: 'నా విషయాలు',
    allSubjects: 'అన్ని విషయాలు',
    books: 'పుస్తకాలు',
    chapters: 'అధ్యాయాలు',
    notes: 'గమనికలు',
    quizzes: 'క్విజ్‌లు',
    qa: 'ప్ర&జ',
    searchPlaceholder: 'పుస్తకాలు, అధ్యాయాలను వెతకండి...',
    noBooks: 'పుస్తకాలు కనుగొనబడలేదు',
    noChapters: 'అధ్యాయాలు అందుబాటులో లేవు',
    noNotes: 'గమనికలు అందుబాటులో లేవు',
    noQuizzes: 'క్విజ్‌లు అందుబాటులో లేవు',
    startReading: 'చదవడం ప్రారంభించండి',
    continueReading: 'చదవడం కొనసాగించండి',
    takeQuiz: 'క్విజ్ తీసుకోండి',
    viewDetails: 'వివరాలు చూడండి',
    chapterNumber: 'అధ్యాయం',
    totalChapters: 'అధ్యాయాలు',
    notesCount: 'గమనికలు',
    quizzesCount: 'క్విజ్‌లు',
  },
  mr: {
    title: 'ग्रंथालय',
    mySubjects: 'माझे विषय',
    allSubjects: 'सर्व विषय',
    books: 'पुस्तके',
    chapters: 'प्रकरणे',
    notes: 'नोट्स',
    quizzes: 'प्रश्नमंजुषा',
    qa: 'प्र&उ',
    searchPlaceholder: 'पुस्तके, प्रकरणे शोधा...',
    noBooks: 'पुस्तके सापडली नाहीत',
    noChapters: 'प्रकरणे उपलब्ध नाहीत',
    noNotes: 'नोट्स उपलब्ध नाहीत',
    noQuizzes: 'प्रश्नमंजुषा उपलब्ध नाहीत',
    startReading: 'वाचणे सुरू करा',
    continueReading: 'वाचणे सुरू ठेवा',
    takeQuiz: 'प्रश्नमंजुषा सोडवा',
    viewDetails: 'तपशील पहा',
    chapterNumber: 'प्रकरण',
    totalChapters: 'प्रकरणे',
    notesCount: 'नोट्स',
    quizzesCount: 'प्रश्नमंजुषा',
  },
  bn: {
    title: 'লাইব্রেরি',
    mySubjects: 'আমার বিষয়',
    allSubjects: 'সমস্ত বিষয়',
    books: 'বই',
    chapters: 'অধ্যায়',
    notes: 'নোট',
    quizzes: 'কুইজ',
    qa: 'প্র&উ',
    searchPlaceholder: 'বই, অধ্যায় খুঁজুন...',
    noBooks: 'কোন বই পাওয়া যায়নি',
    noChapters: 'কোন অধ্যায় উপলব্ধ নেই',
    noNotes: 'কোন নোট উপলব্ধ নেই',
    noQuizzes: 'কোন কুইজ উপলব্ধ নেই',
    startReading: 'পড়া শুরু করুন',
    continueReading: 'পড়া চালিয়ে যান',
    takeQuiz: 'কুইজ নিন',
    viewDetails: 'বিবরণ দেখুন',
    chapterNumber: 'অধ্যায়',
    totalChapters: 'অধ্যায়',
    notesCount: 'নোট',
    quizzesCount: 'কুইজ',
  },
};
