export const onboarding = {
  en: {
    title: 'Let\'s personalize your experience',
    subtitle: 'Tell us about yourself to get started',
    selectRole: 'I am a...',
    student: 'Student',
    teacher: 'Teacher',
    parent: 'Parent',
    selectBoard: 'Select your Board',
    selectClass: 'Select your Class',
    selectMedium: 'Select your Medium',
    selectSubjects: 'Select your Subjects',
    selectGoals: 'What are your goals?',
    dailyStudy: 'Daily Study',
    weeklyQuiz: 'Weekly Quiz',
    readingStreak: 'Reading Streak',
    next: 'Next',
    back: 'Back',
    finish: 'Finish',
    skip: 'Skip',
    step: 'Step',
    of: 'of',
  },
  hi: {
    title: 'आइए अपने अनुभव को वैयक्तिकृत करें',
    subtitle: 'शुरू करने के लिए हमें अपने बारे में बताएं',
    selectRole: 'मैं हूं...',
    student: 'छात्र',
    teacher: 'शिक्षक',
    parent: 'माता-पिता',
    selectBoard: 'अपना बोर्ड चुनें',
    selectClass: 'अपनी कक्षा चुनें',
    selectMedium: 'अपना माध्यम चुनें',
    selectSubjects: 'अपने विषय चुनें',
    selectGoals: 'आपके लक्ष्य क्या हैं?',
    dailyStudy: 'दैनिक अध्ययन',
    weeklyQuiz: 'साप्ताहिक प्रश्नोत्तरी',
    readingStreak: 'पढ़ने की लकीर',
    next: 'आगे',
    back: 'पीछे',
    finish: 'समाप्त',
    skip: 'छोड़ें',
    step: 'चरण',
    of: 'का',
  },
  ta: {
    title: 'உங்கள் அனுபவத்தை தனிப்பயனாக்குவோம்',
    subtitle: 'தொடங்க உங்களைப் பற்றி எங்களிடம் கூறுங்கள்',
    selectRole: 'நான் ஒரு...',
    student: 'மாணவர்',
    teacher: 'ஆசிரியர்',
    parent: 'பெற்றோர்',
    selectBoard: 'உங்கள் வாரியத்தைத் தேர்ந்தெடுக்கவும்',
    selectClass: 'உங்கள் வகுப்பைத் தேர்ந்தெடுக்கவும்',
    selectMedium: 'உங்கள் ஊடகத்தைத் தேர்ந்தெடுக்கவும்',
    selectSubjects: 'உங்கள் பாடங்களைத் தேர்ந்தெடுக்கவும்',
    selectGoals: 'உங்கள் இலக்குகள் என்ன?',
    dailyStudy: 'தினசரி படிப்பு',
    weeklyQuiz: 'வாராந்திர வினாடி வினா',
    readingStreak: 'வாசிப்பு தொடர்ச்சி',
    next: 'அடுத்து',
    back: 'பின்னால்',
    finish: 'முடி',
    skip: 'தவிர்க்கவும்',
    step: 'படி',
    of: 'இன்',
  },
  te: {
    title: 'మీ అనుభవాన్ని వ్యక్తిగతీకరించుకుందాం',
    subtitle: 'ప్రారంభించడానికి మీ గురించి మాకు చెప్పండి',
    selectRole: 'నేను...',
    student: 'విద్యార్థి',
    teacher: 'ఉపాధ్యాయుడు',
    parent: 'తల్లిదండ్రులు',
    selectBoard: 'మీ బోర్డును ఎంచుకోండి',
    selectClass: 'మీ తరగతిని ఎంచుకోండి',
    selectMedium: 'మీ మాధ్యమాన్ని ఎంచుకోండి',
    selectSubjects: 'మీ విషయాలను ఎంచుకోండి',
    selectGoals: 'మీ లక్ష్యాలు ఏమిటి?',
    dailyStudy: 'రోజువారీ అధ్యయనం',
    weeklyQuiz: 'వారపు క్విజ్',
    readingStreak: 'చదివే పరంపర',
    next: 'తర్వాత',
    back: 'వెనుకకు',
    finish: 'ముగించు',
    skip: 'దాటవేయి',
    step: 'అడుగు',
    of: 'లో',
  },
  mr: {
    title: 'चला तुमचा अनुभव वैयक्तिकृत करूया',
    subtitle: 'सुरुवात करण्यासाठी आम्हाला तुमच्याबद्दल सांगा',
    selectRole: 'मी आहे...',
    student: 'विद्यार्थी',
    teacher: 'शिक्षक',
    parent: 'पालक',
    selectBoard: 'तुमचा बोर्ड निवडा',
    selectClass: 'तुमचा वर्ग निवडा',
    selectMedium: 'तुमचे माध्यम निवडा',
    selectSubjects: 'तुमचे विषय निवडा',
    selectGoals: 'तुमची उद्दिष्टे काय आहेत?',
    dailyStudy: 'दैनिक अभ्यास',
    weeklyQuiz: 'साप्ताहिक प्रश्नमंजुषा',
    readingStreak: 'वाचन शृंखला',
    next: 'पुढे',
    back: 'मागे',
    finish: 'समाप्त',
    skip: 'वगळा',
    step: 'पायरी',
    of: 'चा',
  },
  bn: {
    title: 'আসুন আপনার অভিজ্ঞতা ব্যক্তিগতকৃত করি',
    subtitle: 'শুরু করতে আমাদের নিজের সম্পর্কে বলুন',
    selectRole: 'আমি একজন...',
    student: 'ছাত্র',
    teacher: 'শিক্ষক',
    parent: 'পিতামাতা',
    selectBoard: 'আপনার বোর্ড নির্বাচন করুন',
    selectClass: 'আপনার ক্লাস নির্বাচন করুন',
    selectMedium: 'আপনার মাধ্যম নির্বাচন করুন',
    selectSubjects: 'আপনার বিষয় নির্বাচন করুন',
    selectGoals: 'আপনার লক্ষ্য কি?',
    dailyStudy: 'দৈনিক অধ্যয়ন',
    weeklyQuiz: 'সাপ্তাহিক কুইজ',
    readingStreak: 'পড়ার ধারা',
    next: 'পরবর্তী',
    back: 'পিছনে',
    finish: 'শেষ',
    skip: 'এড়িয়ে যান',
    step: 'ধাপ',
    of: 'এর',
  },
};
