export const profile = {
  en: {
    profile: 'Profile',
    editProfile: 'Edit Profile',
    settings: 'Settings',
    logout: 'Logout',
    followers: 'Followers',
    following: 'Following',
    posts: 'Posts',
    follow: 'Follow',
    unfollow: 'Unfollow',
    bio: 'Bio',
    activity: 'Activity',
    achievements: 'Achievements',
    stats: 'Stats',
    studyStreak: 'Study Streak',
    days: 'days',
    points: 'Points',
    quizzesTaken: 'Quizzes Taken',
    notesRead: 'Notes Read',
    changeTheme: 'Theme',
    language: 'Language',
    notifications: 'Notifications',
    privacy: 'Privacy',
    about: 'About',
    help: 'Help',
    termsOfService: 'Terms of Service',
    privacyPolicy: 'Privacy Policy',
  },
  hi: {
    profile: 'प्रोफ़ाइल',
    editProfile: 'प्रोफ़ाइल संपादित करें',
    settings: 'सेटिंग्स',
    logout: 'लॉगआउट',
    followers: 'फ़ॉलोअर्स',
    following: 'फ़ॉलोइंग',
    posts: 'पोस्ट',
    follow: 'फ़ॉलो करें',
    unfollow: 'अनफ़ॉलो करें',
    bio: 'बायो',
    activity: 'गतिविधि',
    achievements: 'उपलब्धियां',
    stats: 'आंकड़े',
    studyStreak: 'अध्ययन लकीर',
    days: 'दिन',
    points: 'अंक',
    quizzesTaken: 'प्रश्नोत्तरी ली गई',
    notesRead: 'नोट्स पढ़े गए',
    changeTheme: 'थीम',
    language: 'भाषा',
    notifications: 'सूचनाएं',
    privacy: 'गोपनीयता',
    about: 'बारे में',
    help: 'मदद',
    termsOfService: 'सेवा की शर्तें',
    privacyPolicy: 'गोपनीयता नीति',
  },
  ta: {
    profile: 'சுயவிவரம்',
    editProfile: 'சுயவிவரத்தை திருத்து',
    settings: 'அமைப்புகள்',
    logout: 'வெளியேறு',
    followers: 'பின்தொடர்பவர்கள்',
    following: 'பின்தொடர்தல்',
    posts: 'இடுகைகள்',
    follow: 'பின்தொடர',
    unfollow: 'பின்தொடர்வதை நிறுத்து',
    bio: 'சுயவிவரம்',
    activity: 'செயல்பாடு',
    achievements: 'சாதனைகள்',
    stats: 'புள்ளிவிவரங்கள்',
    studyStreak: 'படிப்பு தொடர்ச்சி',
    days: 'நாட்கள்',
    points: 'புள்ளிகள்',
    quizzesTaken: 'எடுக்கப்பட்ட வினாடி வினாக்கள்',
    notesRead: 'படிக்கப்பட்ட குறிப்புகள்',
    changeTheme: 'தீம்',
    language: 'மொழி',
    notifications: 'அறிவிப்புகள்',
    privacy: 'தனியுரிமை',
    about: 'பற்றி',
    help: 'உதவி',
    termsOfService: 'சேவை விதிமுறைகள்',
    privacyPolicy: 'தனியுரிமை கொள்கை',
  },
  te: {
    profile: 'ప్రొఫైల్',
    editProfile: 'ప్రొఫైల్ సవరించండి',
    settings: 'సెట్టింగ్‌లు',
    logout: 'లాగ్అవుట్',
    followers: 'ఫాలోవర్లు',
    following: 'ఫాలోయింగ్',
    posts: 'పోస్ట్‌లు',
    follow: 'ఫాలో చేయండి',
    unfollow: 'అన్‌ఫాలో చేయండి',
    bio: 'బయో',
    activity: 'కార్యకలాపాలు',
    achievements: 'సాధనలు',
    stats: 'గణాంకాలు',
    studyStreak: 'అధ్యయన పరంపర',
    days: 'రోజులు',
    points: 'పాయింట్లు',
    quizzesTaken: 'తీసుకున్న క్విజ్‌లు',
    notesRead: 'చదివిన గమనికలు',
    changeTheme: 'థీమ్',
    language: 'భాష',
    notifications: 'నోటిఫికేషన్‌లు',
    privacy: 'గోప్యత',
    about: 'గురించి',
    help: 'సహాయం',
    termsOfService: 'సేవా నిబంధనలు',
    privacyPolicy: 'గోప్యతా విధానం',
  },
  mr: {
    profile: 'प्रोफाइल',
    editProfile: 'प्रोफाइल संपादित करा',
    settings: 'सेटिंग्ज',
    logout: 'लॉगआउट',
    followers: 'फॉलोअर्स',
    following: 'फॉलोइंग',
    posts: 'पोस्ट',
    follow: 'फॉलो करा',
    unfollow: 'अनफॉलो करा',
    bio: 'बायो',
    activity: 'क्रियाकलाप',
    achievements: 'उपलब्धी',
    stats: 'आकडेवारी',
    studyStreak: 'अभ्यास शृंखला',
    days: 'दिवस',
    points: 'गुण',
    quizzesTaken: 'प्रश्नमंजुषा घेतल्या',
    notesRead: 'नोट्स वाचल्या',
    changeTheme: 'थीम',
    language: 'भाषा',
    notifications: 'सूचना',
    privacy: 'गोपनीयता',
    about: 'बद्दल',
    help: 'मदत',
    termsOfService: 'सेवा अटी',
    privacyPolicy: 'गोपनीयता धोरण',
  },
  bn: {
    profile: 'প্রোফাইল',
    editProfile: 'প্রোফাইল সম্পাদনা',
    settings: 'সেটিংস',
    logout: 'লগআউট',
    followers: 'ফলোয়ার',
    following: 'ফলোয়িং',
    posts: 'পোস্ট',
    follow: 'ফলো',
    unfollow: 'আনফলো',
    bio: 'বায়ো',
    activity: 'কার্যকলাপ',
    achievements: 'অর্জন',
    stats: 'পরিসংখ্যান',
    studyStreak: 'অধ্যয়ন ধারা',
    days: 'দিন',
    points: 'পয়েন্ট',
    quizzesTaken: 'কুইজ নেওয়া হয়েছে',
    notesRead: 'নোট পড়া হয়েছে',
    changeTheme: 'থিম',
    language: 'ভাষা',
    notifications: 'বিজ্ঞপ্তি',
    privacy: 'গোপনীয়তা',
    about: 'সম্পর্কে',
    help: 'সাহায্য',
    termsOfService: 'সেবা পাবার শর্ত',
    privacyPolicy: 'গোপনীয়তা নীতি',
  },
};
